version: "3.8"
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - "3000:3000"
    restart: always
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "3001:3001"
    restart: always